export default [
	'Abt-Wolfram-Ring',
	'Abtissensee',
	'Abtsberg',
	'Adalbert-Stifter-Straße',
	'Adalbertstraße',
	'Adam-Krafft-Straße',
	'Adam-Senger-Straße',
	'Adam-Stegerwald-Straße',
	'Adolf-Kolping-Straße',
	'Adolf-Wächter-Straße',
	'Agnes-Schwanfelder-Straße',
	'Agnesstraße',
	'Ahornstraße',
	'Akazienweg',
	'Albrecht-Dürer-Straße',
	'Albrecht-von-Eyb-Leite',
	'Alte Seilerei',
	'Altenburg',
	'Altenburger Straße',
	'Alter Graben',
	'Alter Knock',
	'Am Bildlein',
	'Am Börstig',
	'Am Bundleshof',
	'Am Campingplatz',
	'Am Friedrichsbrunnen',
	'Am Hahnenweg',
	'Am Heidelsteig',
	'Am Hirschknock',
	'Am Hochgericht',
	'Am Hollergraben',
	'Am Kanal',
	'Am Knöcklein',
	'Am Kranen',
	'Am Leinritt',
	'Am Luitpoldhain',
	'Am Melbersee',
	'Am Pinzighof',
	'Am Regnitzufer',
	'Am Roten Knock',
	'Am Rotgraben',
	'Am Sendelbach',
	'Am Spinnseyer',
	'Am Sportplatz',
	'Am Steinberg',
	'Am Steinknock',
	'Am Tännig',
	'Am Uferholz',
	'Am Weidenbrunnen',
	'Am Weidenufer',
	'Am Weingarten',
	'Am Werkkanal',
	'Am Zwinger',
	'Amalienstraße',
	'Amselweg',
	'An Den Stadtmauern',
	'An den Wachsbleichen',
	'An der Breitenau',
	'An der Kettenstraße',
	'an Der Spinnerei',
	'An der Spinnerei',
	'An der Universität',
	'an Der Weberei',
	'An der Weberei',
	'An Der Ziegelei',
	'Andreas-Hofer-Straße',
	'Andreas-Lang-Steig',
	'Angerstraße',
	'Anna-Linder-Platz',
	'Anna-Maria-Junius-Straße',
	'Annastraße',
	'Anton-Schuster-Straße',
	'Anwanderstraße',
	'Armeestraße',
	'Arndtstraße',
	'Aronstraße',
	'Artur-Landgraf-Straße',
	'Aubachstraße',
	'Auf dem Lerchenbühl',
	'Auf der Höhe',
	'Aufbaustraße',
	'Aufseßhöflein',
	'Aufseßstraße',
	'Augustenstraße',
	'Äußere Galgenfuhr',
	'Äußere Löwenstraße',
	'Austraße',
	'Babenbergerring',
	'Badstraße',
	'Balthasar-Neumann-Straße',
	'Balthasargäßchen',
	'Bamberger Straße',
	'Bamberger Weg',
	'Banscherhof',
	'Bas 29',
	'Bauchwitzstraße',
	'Baunacher Straße',
	'Benkertstraße',
	'Benzstraße',
	'Bergstraße',
	'Bergweg',
	'Berliner Ring',
	'Bienenweg',
	'Biergartenweg',
	'Bierkrugweg',
	'Birkenallee',
	'Birkengraben',
	'Bischofsmühlbrücke',
	'Bleichanger',
	'Blumenstraße',
	'Bonhoefferplatz',
	'Böttgerstraße',
	'Boveristraße',
	'Brahmann-Ring',
	'Brauerei Keesmann Weg',
	'Breitäckerstraße',
	'Brennerstraße',
	'Breslaustraße',
	'Broseggoweechla',
	'Brückenstraße',
	'Bruckertshofer Straße',
	'Bruderwaldstraße',
	'Brunnenstraße',
	'Brunnenweg',
	'Buchenstraße',
	'Buger Hauptstraße',
	'Buger Straße',
	'Bughof',
	'Bughofer Straße',
	'Bullistraße',
	'Burgheimer Lage',
	'Carl-Meinelt-Straße',
	'Carl-Schmolz-Weg',
	'Caspersmeyerstraße',
	'Cherbonhofstraße',
	'Christophorusweg',
	'Clarissenweg',
	'Claviusstraße',
	'Coburger Straße',
	'Concordiastraße',
	'Die Bergner',
	'Die Krött',
	'Dientzenhoferstraße',
	'Dieselstraße',
	'Distelweg',
	'Doktor Hans-Neubauer-Straße',
	'Dominikanerstraße',
	'Domplatz',
	'Domstraße',
	'Don-Bosco-Straße',
	'Dorotheenstraße',
	'Dr.-Eisenbart-Hof',
	'Dr.-Haas-Straße',
	'Dr.-Hans-Ehard-Straße',
	'Dr.-Hans-Neubauer-Straße',
	'Dr.-Ida-Noddack-Straße',
	'Dr.-Martinet-Straße',
	'Dr.-Rattel-Straße',
	'Dr.-Remeis-Straße',
	'Dr.-Robert-Pfleger-Straße',
	'Dr.-Thomas-Dehler-Straße',
	'Dr.-Von-Schmitt-Str.',
	'Dr.-von-Schmitt-Straße',
	'Dunantstraße',
	'Dürrseestraße',
	'Dürrwächterstraße',
	'E.T.A.-Hoffmann-Platz',
	'E.T.A.-Hoffmann-Straße',
	'Eberhardtstraße',
	'Ebermannstadter Straße',
	'Eckbertstraße',
	'Edelstraße',
	'Egelseestraße',
	'Eichelseeweg',
	'Eichendorffplatz',
	'Eichendorffstraße',
	'Eichenweg',
	'Eisgrube',
	'Elisabethenstraße',
	'Ellen-Ammann-Straße',
	'Elsa-Brändström-Straße',
	'Elsterweg',
	'Erlenweg',
	'Erlenweg',
	'Erlichstraße',
	'Ernst-Zinner-Straße',
	'Eschenweg',
	'Esztergomstraße',
	'Eugen-Pacelli-Platz',
	'Ezzostraße',
	'Fabrikbau',
	'Fabrikhof',
	'Färbergasse',
	'Farnweg',
	'Feldkirchenstraße',
	'Ferdinand-Braun-Straße',
	'Ferdinand-Tietz-Straße',
	'Feuerwehrzufahrt',
	'Fichtestraße',
	'Fischerei',
	'Fischergasse',
	'Fischerhof',
	'Fischstraße',
	'Fleischstraße',
	'Flößergasse',
	'Fohlengartenstraße',
	'Föhrenstraße',
	'Forchheimer Straße',
	'Fortenbachweg',
	'Frankenwaldstraße',
	'Franz-Ludwig-Straße',
	'Franziskanergasse',
	'Frauenplatz',
	'Frauenstraße',
	'Fraunbergstraße',
	'Fraunhoferstraße',
	'Friede-Nadig-Straße',
	'Friedrich-Ebert-Straße',
	'Friedrichstraße',
	'Fritz-Bayerlein-Weg',
	'Fritz-Eberle-Straße',
	'Frutolfstraße',
	'Gabelsbergerstraße',
	'Gackensteinweg',
	'Galgenfuhr',
	'Galgenfuhr',
	'Gangolfplatz',
	'Gangolfsplatz',
	'Gangolfsweg',
	'Garagenweg',
	'Gartenstädter Markt',
	'Gartenstraße',
	'Gasfabrikstraße',
	'Gaustadter Hauptstraße',
	'Gebrüder-Pfau-Straße',
	'Geheimrat-Heß-Ring',
	'Geisfelder Straße',
	'Generalsgasse',
	'Georg-Herrmannsdörfer-Ring',
	'Georg-Mann-Straße',
	'Georgendamm',
	'Georgenstraße',
	'Gerberstraße',
	'Gereuthstraße',
	'Gerhart-Hauptmann-Straße',
	'Gertraudenstraße',
	'Geschwister-Scholl-Ring',
	'Geyerswörthplatz',
	'Geyerswörthstraße',
	'Ginsterweg',
	'Giselastraße',
	'Goethestraße',
	'Gollwitzerstraße',
	'Gönnerstraße',
	'Grabfeldstraße',
	'Graf-Arnold-Straße',
	'Graf-Stauffenberg-Platz',
	'Grafensteinstraße',
	'Gräserfeldweg',
	'Greiffenbergstraße',
	'Grüner Markt',
	'Grünhundsbrunnen',
	'Grüntalstraße',
	'Gumboldsleite',
	'Gundelsheimer Straße',
	'Guntherstraße',
	'Gutenbergstraße',
	'Guts-Muths-Straße',
	'Habergasse',
	'Hafenstraße',
	'Häfnerstraße',
	'Hahnwaldweg',
	'Hainstraße',
	'Halbäcker',
	'Hallstadter Straße',
	'Hans-Birkmayr-Straße',
	'Hans-Böckler-Straße',
	'Hans-Morper-Straße',
	'Hans-Schmitt-Straße',
	'Hans-Schütz-Straße',
	'Hans-Wölfel-Straße',
	'Harthstraße',
	'Härtleinstraße',
	'Hartmannstraße',
	'Hasengasse',
	'Haßbergestraße',
	'Hauptsmoorstraße',
	'Hauptwachstraße',
	'Hauptweg',
	'Hedwigstraße',
	'Hegelstraße',
	'Heidengasse',
	'Heiliggrabstraße',
	'Heimfriedweg',
	'Heinkelmannstraße',
	'Heinrich-Manz-Straße',
	'Heinrich-Semlinger-Straße',
	'Heinrich-Weber-Platz',
	'Heinrichsdamm',
	'Heinrichshöhe',
	'Heinrichstraße',
	'Helene-Weber-Straße',
	'Hellerstraße',
	'Helmholtzstraße',
	'Hemmerleinstraße',
	'Hennebergerstraße',
	'Heringsgraben',
	'Herrenstraße',
	'Hertzstraße',
	'Herzog-Max-Straße',
	'Heßlergasse',
	'Hetzerstraße',
	'Heumannstraße',
	'Heumarkt',
	'Heunischstraße',
	'Hezilostraße',
	'Hildegardstraße',
	'Hiltnerstraße',
	'Himmelreichstraße',
	'Hinrich-Wichern-Straße',
	'Hinterer Bach',
	'Hinterer Graben',
	'Hinterer Knock',
	'Hinterer Sückleinsweg',
	'Hirschbühlstraße',
	'Hirtenstraße',
	'Höcherbühl',
	'Höfener Weg',
	'Hohe-Kreuz-Straße',
	'Hohenlohestraße',
	'Hohenstauferstraße',
	'Höhenstraße',
	'Hohmannstraße',
	'Hölle',
	'Holunderweg',
	'Holzfeldweg',
	'Holzgartenstraße',
	'Holzmarkt',
	'Hopfengartenstraße',
	'Hopfferstraße',
	'Hornthalstraße',
	'Hubertusstraße',
	'Hüttenfeldstraße',
	'Ignaz-Wolf-Straße',
	'Im Bauernfeld',
	'Im Dunster',
	'Im Eichhorn',
	'Im Färbersgarten',
	'Im Kapellenschlag',
	'Im Kramersfeld',
	'Im Sücklein',
	'Im Wiesengrund',
	'Immenhofweg',
	'In der Südflur',
	'In der Warth',
	'Innere Löwenstraße',
	'Jäckstraße',
	'Jacobus-von-Hauck-Platz',
	'Jägerstraße',
	'Jahnstraße',
	'Jakobsberg',
	'Jakobsplatz',
	'Jesuitenstraße',
	'Johannes-Hoffmann-Straße',
	'John-F.-Kennedy_Boulevard',
	'John-F.-Kennedy-Boulevard',
	'Josef-Kindshoven-Straße',
	'Josef-Manger-Straße',
	'Josefstraße',
	'Joseph-Otto-Kolb-Straße',
	'Josephstraße',
	'Judenstraße',
	'Jungfernleite',
	'Jungkreutstraße',
	'Jurastraße',
	'Kai 2',
	'Kai 3',
	'Kai 5',
	'Kaimsgasse',
	'Kaipershof',
	'Kammermeisterweg',
	'Kammstraße',
	'Kanonikus-Schwab-Straße',
	'Kantstraße',
	'Kapellenstraße',
	'Kapuzinerstraße',
	'Karl-Leicht-Straße',
	'Karl-May-Straße',
	'Karmelitenplatz',
	'Kärntenstraße',
	'Karolinenstraße',
	'Kasernstraße',
	'Kaspar-Schulz-Straße',
	'Kaspar-Zeuß-Weg',
	'Kastanienstraße',
	'Katharinenhof',
	'Katharinenstraße',
	'Katzenberg',
	'Katzheimerstraße',
	'Kemmerstraße',
	'Keßlerstraße',
	'Kettenbrücke',
	'Kettenbrückstraße',
	'Kiefernstraße',
	'Kindleinseiche',
	'Kirchweg',
	'Kirschäckerstraße',
	'Kirschenweg',
	'Kleberstraße',
	'Kleebaumsgasse',
	'Kleinseeweg',
	'Kloster-Banz-Straße',
	'Kloster-Langheim-Straße',
	'Klosterstraße',
	'Klubenspiesweg',
	'Knödelgasse',
	'Köhlerstraße',
	'König-Konrad-Straße',
	'Königsweg',
	'Konrad-Fink-Straße',
	'Kopernikusstraße',
	'Koppenhofgasse',
	'Kornstraße',
	'Krackhardtstraße',
	'Kroatengasse',
	'Kronacher Straße',
	'Krötleinstraße',
	'Küchelstraße',
	'Kunigundendamm',
	'Kunigundenruhstraße',
	'Kunigundenweg',
	'Lagerhausstraße',
	'Langackerweg',
	'Lange Äcker',
	'Lange Straße',
	'Langgartenstraße',
	'Laubanger',
	'Laurenziplatz',
	'Laurenzistraße',
	'Lebergasse',
	'Leiten',
	'Lerchenweg',
	'Letzengasse',
	'Leyackerweg',
	'Lichtenhaidestraße',
	'Lindenanger',
	'Linderstraße',
	'Lobenhofferstraße',
	'Looshornweg',
	'Lorbersgasse',
	'Lorenz-Krapp-Straße',
	'Ludwigshöhe',
	'Ludwigstraße',
	'Lugbank',
	'Luisenstraße',
	'Luitpoldstraße',
	'Magazinstraße',
	'Magdalenenstraße',
	'Mahrs Bräu Weg',
	'Maienbrunnen',
	'Mainluststraße',
	'Mainstraße',
	'Mannlehenweg',
	'Mannshalm',
	'Margaretendamm',
	'Maria-Lerch-Weg',
	'Maria-Ward-Straße',
	'Marie-Juchacz-Straße',
	'Marienbrücke',
	'Marienplatz',
	'Marienstraße',
	'Markusplatz',
	'Markusstraße',
	'Martin-Luther-Straße',
	'Martin-Ott-Straße',
	'Maternstraße',
	'Mattenheimerstraße',
	'Mautgasse',
	'Max-Planck-Straße',
	'Max-Schäfer-Straße',
	'Maximiliansplatz',
	'Meinhardtstraße',
	'Memmelsdorfer Straße',
	'Meranierstraße',
	'Messerschmittstraße',
	'Michael-Rümmer-Straße',
	'Michel-Raulino-Straße',
	'Michelsberg',
	'Michelsberger Straße',
	'Milchweg',
	'Minna-Neuburger-Straße',
	'Mittelbachstraße',
	'Mittelstraße',
	'Mittlere Seelgasse',
	'Mittlere Sterngasse',
	'Mittlerer Kaulberg',
	'Mohnstraße',
	'Molitorgasse',
	'Mönchsleite',
	'Moosstraße',
	'Mühlwörth',
	'Müllerfeldweg',
	'Münchner Ring',
	'Münzmeisterstraße',
	'Mußstraße',
	'Mutschelleweg',
	'Nathan-R.-Preston-Straße',
	'Nebingerhof',
	'Neue Bughofer Straße',
	'Neuerbstraße',
	'Nikolaus-Lenau-Ring',
	'Nonnenbrücke',
	'Nürnberger Straße',
	'Obere Brücke',
	'Obere Dorotheenstraße',
	'Obere Karolinenstraße',
	'Obere Königstraße',
	'Obere Mühlbrücke',
	'Obere Sandstraße',
	'Obere Schildstraße',
	'Obere Seelgasse',
	'Obere Sterngasse',
	'Oberer Kaulberg',
	'Oberer Leinritt',
	'Oberer Stephansberg',
	'Oberes Gäßchen',
	'Obstmarkt',
	'Ochsenanger',
	'Ohlmüllerstraße',
	'Ohmstraße',
	'Ottobrunnen',
	'Ottoplatz',
	'Ottostraße',
	'Panzerleite',
	'Panzerstraße',
	'Pappelweg',
	'Paracelsusstraße',
	'Paradiesweg',
	'Paul-Keller-Ring',
	'Pelzmühlweg',
	'Pestalozzistraße',
	'Peter-Link-Straße',
	'Peter-Schneider-Straße',
	'Petrinistraße',
	'Peuntstraße',
	'Pfahlplätzchen',
	'Pfarrer-Kneipp-Hof',
	'Pfarrfeldstraße',
	'Pfarrgasse',
	'Pfeuferstraße',
	'Pfisterstraße',
	'Platanenallee',
	'Plattengasse',
	'Plattnergasse',
	'Pleinserhof',
	'Pödeldorfer Straße',
	'Prälat-Meixner-Platz',
	'Promenadestraße',
	'Pulvergasse',
	'Raatschkatlweg',
	'Rattlerstraße',
	'Regensburger Ring',
	'Regnitzstraße',
	'Reitersfeldweg',
	'Renkfeldweg',
	'Rennsteig',
	'Residenzstraße',
	'Reußstraße',
	'Rhein-Main-Donau-Damm',
	'Rheinstraße',
	'Richard-Wagner-Straße',
	'Richthofenstraße',
	'Riegelhofgasse',
	'Riemenschneiderstraße',
	'Ringleinsgasse',
	'Rinnersteig',
	'Robert-Bosch-Straße',
	'Robert-Koch-Straße',
	'Rodelbahn',
	'Rodezstraße',
	'Röntgenstraße',
	'Roppeltsgasse',
	'Rosa-Kempf-Straße',
	'Rosa-Parks-Straße',
	'Rosengasse',
	'Rosmarinweg',
	'Rößleinsweg',
	'Rotdornweg',
	'Rotensteinstraße',
	'Röthelbachweg',
	'Rothofer Straße',
	'Rothofer Weg',
	'Rothofleite',
	'Rückertstraße',
	'Rüdelweg',
	'Salierstraße',
	'Sandbad',
	'Sankt-Wolfgang-Platz',
	'Schäuferlaweg',
	'Schellenbergerstraße',
	'Scheubelstraße',
	'Schiffbauplatz',
	'Schildstraße',
	'Schillerplatz',
	'Schimmelsgasse',
	'Schlagfeldweg',
	'Schlehdornweg',
	'Schlenkerla Gasse',
	'Schloßstraße',
	'Schlüsselbergerstraße',
	'Schlüsselstraße',
	'Schneisenweg',
	'Schönbornstraße',
	'Schönleinsplatz',
	'Schorkstraße',
	'Schranne',
	'Schreiberstraße',
	'Schrottenberggasse',
	'Schubertshof',
	'Schulgasse',
	'Schulplatz',
	'Schützenstraße',
	'Schwarzenbergstraße',
	'Schweinfurter Straße',
	'Schweitzerstraße',
	'Seefriedweg',
	'Seehofstraße',
	'Seewiesenstraße',
	'Seinsheimstraße',
	'Semmelweisstraße',
	'Siechenstraße',
	'Siedlungsweg',
	'Siemensstraße',
	'Sodalenruh',
	'Sodenstraße',
	'Sonnenplätzchen',
	'Sonnleithe',
	'Spiegelgraben',
	'Spitalstraße',
	'St.-Getreu-Straße',
	'St.-Wolfgang-Platz',
	'Staffelbergweg',
	'Stammfeldstraße',
	'Stangsstraße',
	'Starkenfeldstraße',
	'Stauffenbergstraße',
	'Stazinäriweg',
	'Stegauracher Straße',
	'Steigerwaldstraße',
	'Steinertstraße',
	'Steinweg',
	'Stephansplatz',
	'Sternwartstraße',
	'Storchsgasse',
	'Strickerstraße',
	'Strullendorfer Straße',
	'Sturzstraße',
	'Sudetenstraße',
	'Suidgerstraße',
	'Süßholzweg',
	'Sutristraße',
	'Sutte',
	'Sylvanerweg',
	'Synagogenplatz',
	'Tarvisstraße',
	'Teufelsgraben',
	'Theatergassen',
	'Theilerstraße',
	'Theodor-Heuss-Ring',
	'Theodor-Mathieu-Straße',
	'Theresienstraße',
	'Theuerstadt',
	'Thorackerstraße',
	'Titusstraße',
	'Tocklergasse',
	'Tränkgasse',
	'Trautmannstraße',
	'Treustraße',
	'Trimbergstraße',
	'Troppauplatz',
	'Ulanenplatz',
	'Ulmenstraße',
	'Unterauracher Weg',
	'Untere Brücke',
	'Untere Königstraße',
	'Untere Mühlbrücke',
	'Untere Sandstraße',
	'Untere Seelgasse',
	'Untere Sterngasse',
	'Unterer Kaulberg',
	'Unterer Leinritt',
	'Unterer Stephansberg',
	'Urbanstraße',
	'Valentin-Becker-Straße',
	'Valentin-Rathgeber-Straße',
	'Veit-Stoß-Straße',
	'Viktor-von-Scheffel-Straße',
	'Villachstraße',
	'Vögleinsleite',
	'Vogtstraße',
	'Volkfeldstraße',
	'Von-Helmholtz-Straße',
	'Von-Ketteler-Straße',
	'Von-Reider-Straße',
	'Von-Rotenhan-Straße',
	'Vorderer Bach',
	'Vorderer Graben',
	'Wacholderweg',
	'Wagnersleite',
	'Waizendorfer Straße',
	'Waldstraße',
	'Waldwiesenstraße',
	'Wallenstein-Passage',
	'Walnußweg',
	'Wassermannstraße',
	'Weichselfeld',
	'Weide',
	'Weidendamm',
	'Weiherstraße',
	'Weinbergweg',
	'Weiße Marterstraße',
	'Weißenburgstraße',
	'Wetzelstraße',
	'Weyermannstraße',
	'Wiesenteich',
	'Wildensorger Hauptstraße',
	'Wildensorger Straße',
	'Wilhelmsplatz',
	'Wilhelmstraße',
	'Willostraße',
	'Willy-Lessing-Straße',
	'Winkelweg',
	'Wörthstraße',
	'Wunderburg',
	'Würzburger Straße',
	'Zeppelinstraße',
	'Ziegelgasse',
	'Ziegelhof',
	'Ziegelhüttenstr.',
	'Ziegelhüttenweg',
	'Zieglerschlag',
	'Zinkenwörth',
	'Zollnergäßchen',
	'Zollnerstraße',
	'Zum Eichelberg',
	'Zweidlerweg',
	'Zwerggasse'
];
